#****************************************************************************
# Copyright 2019-2025 Matthew Ballance and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#****************************************************************************
"""Generate a self-contained SV benchmark harness from a zuspec dataclass.

Uses :class:`zuspec.be.sv.rand_class_emitter.SVRandClassEmitter` to produce
the class body, then wraps it with a DPI timing import and a ``module harness``
top-level that drives the randomization loop, prints ``SOL`` lines, and emits
a final ``BENCH_NS`` line.

Usage::

    from zuspec.solver.bench_harness import SolvePerfHarnessGenerator
    gen = SolvePerfHarnessGenerator()
    full_sv = gen.emit(MemTransaction, n_solutions=1000)
    # Write full_sv to a .sv file and compile with Verilator + sv_bench_time.c
"""
from typing import Optional


class SolvePerfHarnessGenerator:
    """Wrap a zuspec dataclass in a complete SV solve-performance harness.

    The generated file is self-contained and can be compiled directly with
    Verilator (plus the DPI C helper ``sv_bench_time.c``)::

        verilator --binary --timing harness.sv sv_bench_time.c --top harness

    Output format
    -------------
    * One ``SOL <field0> <field1> ...`` line per solution  (useful for
      distribution analysis).
    * A final ``BENCH_NS <ns>`` line reporting total wall-clock nanoseconds
      measured by the DPI ``sv_bench_wall_ns()`` function.
    """

    def emit(self, cls: type, n_solutions: int = 1000) -> str:
        """Return a complete, self-contained SV harness file as a string.

        Parameters
        ----------
        cls:
            A ``@zdc.dataclass`` class with ``rand`` fields and
            ``@constraint`` methods.
        n_solutions:
            Default number of solutions when the ``n_solutions`` plusarg is
            not provided at runtime.
        """
        from zuspec.be.sv.rand_class_emitter import SVRandClassEmitter
        import zuspec.dataclasses as zdc

        class_sv = SVRandClassEmitter().emit_class(cls)
        fields = zdc.extract_rand_fields(cls)

        sol_display = self._sol_display(cls.__name__, fields)
        header = self._header(cls.__name__, class_sv, n_solutions, sol_display)
        return header

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _sol_display(self, cls_name: str, fields) -> str:
        """Build the ``$display("SOL ...")`` call for the given fields."""
        fmt_parts = []
        arg_parts = []
        for f in fields:
            fmt_parts.append("%0d")
            arg_parts.append(f"obj.{f['name']}")
        fmt = "SOL " + " ".join(fmt_parts)
        args = ", ".join(arg_parts)
        if args:
            return f'$display("{fmt}", {args});'
        return f'$display("SOL");'

    def _header(self, cls_name: str, class_sv: str, n_solutions: int,
                sol_display: str) -> str:
        # Indent the class_sv block so it reads well inside the file
        class_block = "\n".join("  " + l if l else "" for l in class_sv.splitlines())

        return (
            "// AUTO-GENERATED by SolvePerfHarnessGenerator — do not edit\n"
            "\n"
            'import "DPI-C" function longint sv_bench_wall_ns();\n'
            "\n"
            + class_sv
            + "\n"
            "module harness;\n"
            f"  {cls_name} obj;\n"
            "  int            n_solutions;\n"
            "  int            n;\n"
            "  longint        t_start, t_end;\n"
            "\n"
            "  initial begin\n"
            "    obj = new();\n"
            f"    if (!$value$plusargs(\"n_solutions=%d\", n_solutions))\n"
            f"      n_solutions = {n_solutions};\n"
            "\n"
            "    t_start = sv_bench_wall_ns();\n"
            "    for (n = 0; n < n_solutions; n++) begin\n"
            "      if (obj.randomize() == 0)\n"
            "        $fatal(1, \"randomize() failed at iteration %0d\", n);\n"
            f"      {sol_display}\n"
            "    end\n"
            "    t_end = sv_bench_wall_ns();\n"
            "\n"
            "    $display(\"BENCH_NS %0d\", t_end - t_start);\n"
            "    $finish;\n"
            "  end\n"
            "endmodule\n"
        )
