"""Generate a self-contained C benchmark harness from a zuspec dataclass.

Parallel to SolvePerfHarnessGenerator (SV harness), this emits a C file
that calls the libzsp_solver API directly.  Compile with:

    gcc -O2 -o harness harness.c -lzsp_solver -lm

The generated file is self-contained: it builds the SolveProblem, adds
variables and constraints, then loops N times creating a SolveCtx,
solving, and printing results.
"""
from __future__ import annotations

from typing import Dict, List, Optional, Tuple

from zuspec.dataclasses.ir.expr import BinOp, BoolOp, CmpOp
from zuspec.dataclasses.solver.core.constraints import (
    ConstantConstraint, VariableRefConstraint, BinaryOpConstraint,
    UnaryOpConstraint, BoolOpConstraint, CompareConstraint,
)


# Map IR ops to C enum names
_BINOP_C = {
    BinOp.Add: "BIN_ADD", BinOp.Sub: "BIN_SUB", BinOp.Mult: "BIN_MUL",
    BinOp.Div: "BIN_DIV", BinOp.Mod: "BIN_MOD",
    BinOp.BitAnd: "BIN_BAND", BinOp.BitOr: "BIN_BOR", BinOp.BitXor: "BIN_BXOR",
    BinOp.LShift: "BIN_LSHIFT", BinOp.RShift: "BIN_RSHIFT",
    BinOp.And: "BIN_AND", BinOp.Or: "BIN_OR",
}
_CMPOP_C = {
    CmpOp.Eq: "BIN_EQ", CmpOp.NotEq: "BIN_NEQ",
    CmpOp.Lt: "BIN_LT", CmpOp.LtE: "BIN_LTE",
    CmpOp.Gt: "BIN_GT", CmpOp.GtE: "BIN_GTE",
}


class CSolvePerfHarnessGenerator:
    """Emit a self-contained C benchmark harness for the native solver."""

    def emit(self, cls: type, n_solutions: int = 100000) -> str:
        """Return a complete C source file as a string."""
        from zuspec.dataclasses.solver._core_solve import _extract_struct_type
        from zuspec.dataclasses.solver.frontend.constraint_system_builder import (
            ConstraintSystemBuilder,
        )
        import zuspec.dataclasses as zdc
        import inspect

        # Build the constraint system
        sig = inspect.signature(cls)
        defaults = {
            p.name: (p.default if p.default is not inspect.Parameter.empty else 0)
            for p in sig.parameters.values()
        }
        obj = cls(**defaults)
        struct_type = _extract_struct_type(obj)
        builder = ConstraintSystemBuilder()
        system = builder.build_from_struct(struct_type)

        fields = zdc.extract_rand_fields(cls)
        field_names = [f["name"] for f in fields]

        # Assign variable IDs (same ordering as IRTranslator)
        sorted_names = sorted(system.variables.keys())
        var_id_map = {name: idx for idx, name in enumerate(sorted_names)}

        lines: List[str] = []
        lines.append("// AUTO-GENERATED by CSolvePerfHarnessGenerator")
        lines.append(f"// Source: {cls.__module__} :: {cls.__name__}")
        lines.append("")
        lines.append("#include <stdio.h>")
        lines.append("#include <stdlib.h>")
        lines.append("#include <stdint.h>")
        lines.append("#include <string.h>")
        lines.append("#include <time.h>")
        lines.append('#include "zsp_problem.h"')
        lines.append('#include "zsp_ctx.h"')
        lines.append('#include "zsp_search.h"')
        lines.append('#include "zsp_propagator.h"')
        lines.append("")
        lines.append(f"#define N_VARS {len(sorted_names)}")
        lines.append(f"#define DEFAULT_N_SOLUTIONS {n_solutions}")
        lines.append(f"#define CTX_BUF_SIZE (1 << 20)")
        lines.append("")

        # Build problem function
        lines.append("static void build_problem(SolveProblem *sp) {")

        # Declare variables
        for name, vid in sorted(var_id_map.items(), key=lambda x: x[1]):
            v = system.variables[name]
            lo = v.domain.intervals[0][0] if v.domain.intervals else 0
            hi = v.domain.intervals[-1][1] if v.domain.intervals else 0
            signed = 1 if v.domain.signed else 0
            w = min(v.domain.width, 64)
            lines.append(f"    problem_add_var(sp, {vid}, {w}, {signed}, "
                         f"{lo}LL, {hi}LL);  /* {name} */")

        lines.append("")

        # Add constraints
        self._tmp_counter = 0
        for i, c in enumerate(system.constraints):
            lines.append(f"    /* constraint {i}: {c} */")
            expr_var = self._emit_constraint(lines, var_id_map, c)
            lines.append(f"    problem_add_constraint(sp, {expr_var});")
            lines.append("")

        lines.append("}")
        lines.append("")

        # SOL display format
        fmt_parts = []
        arg_parts = []
        for name in field_names:
            vid = var_id_map.get(name)
            if vid is not None:
                fmt_parts.append("%lld")
                arg_parts.append(f"(long long)solver_get_value(ctx, {vid})")
        sol_fmt = "SOL " + " ".join(fmt_parts) + "\\n"
        sol_args = ", ".join(arg_parts)

        # Main function
        lines.append("int main(int argc, char **argv) {")
        lines.append("    int n_solutions = DEFAULT_N_SOLUTIONS;")
        lines.append("    long long timeout_ns = 0;")
        lines.append("    int quiet = 0;")
        lines.append("    for (int i = 1; i < argc; i++) {")
        lines.append('        if (sscanf(argv[i], "+n_solutions=%d", &n_solutions) == 1) continue;')
        lines.append('        if (sscanf(argv[i], "+timeout_ns=%lld", &timeout_ns) == 1) continue;')
        lines.append('        if (strcmp(argv[i], "-q") == 0) { quiet = 1; continue; }')
        lines.append("    }")
        lines.append("")
        lines.append("    static uint8_t sp_buf[1 << 16];  /* 64 KB for problem data */")
        lines.append("    SolveProblem *sp = solve_problem_init(sp_buf, sizeof(sp_buf));")
        lines.append("    if (!sp) { fprintf(stderr, \"solve_problem_init failed\\n\"); return 1; }")
        lines.append("    build_problem(sp);")
        lines.append("")
        lines.append("    uint8_t *ctx_buf = (uint8_t *)malloc(CTX_BUF_SIZE);")
        lines.append("    struct timespec ts_start, ts_end;")
        lines.append("    clock_gettime(CLOCK_MONOTONIC, &ts_start);")
        lines.append("")
        lines.append("    int n_ok = 0, n_fail = 0, n_timeout = 0;")
        lines.append("    int n;")
        lines.append("    for (n = 0; n < n_solutions; n++) {")
        lines.append("        if (timeout_ns > 0) {")
        lines.append("            struct timespec ts_now;")
        lines.append("            clock_gettime(CLOCK_MONOTONIC, &ts_now);")
        lines.append("            long long elapsed = (ts_now.tv_sec - ts_start.tv_sec) * 1000000000LL")
        lines.append("                              + (ts_now.tv_nsec - ts_start.tv_nsec);")
        lines.append("            if (elapsed >= timeout_ns) break;")
        lines.append("        }")
        lines.append("        void *ba = zsp_block_alloc_create(NULL, CTX_BUF_SIZE);")
        lines.append("        SolveCtx *ctx = solver_create(ctx_buf, CTX_BUF_SIZE, ba);")
        lines.append("        int crc = solver_compile(ctx, sp);")
        lines.append("        if (crc < 0) {")
        lines.append('            fprintf(stderr, "compile failed (rc=%d)\\n", crc);')
        lines.append("            zsp_block_alloc_destroy(ba);")
        lines.append("            return 1;")
        lines.append("        }")
        lines.append("        if (crc > 0) {")
        lines.append('            fprintf(stderr, "ERROR: %d constraint(s) not compiled natively\\n", crc);')
        lines.append("            zsp_block_alloc_destroy(ba);")
        lines.append("            return 1;")
        lines.append("        }")
        lines.append(f"        SolveOpts opts = {{.seed = (uint64_t)n + 1}};")
        lines.append("        SolveResult rc = solver_solve(ctx, &opts);")
        lines.append("        if (rc == SOLVE_UNSAT) {")
        lines.append('            fprintf(stderr, "solve UNSAT at iteration %d\\n", n);')
        lines.append("            n_fail++;")
        lines.append("            zsp_block_alloc_destroy(ba);")
        lines.append("            continue;")
        lines.append("        } else if (rc != SOLVE_OK) {")
        lines.append("            /* SOLVE_TIMEOUT: conflict budget exhausted — expected for some seeds */")
        lines.append('            fprintf(stderr, "solve timeout (rc=%d) at iteration %d\\n", rc, n);')
        lines.append("            n_timeout++;")
        lines.append("            zsp_block_alloc_destroy(ba);")
        lines.append("            continue;")
        lines.append("        }")
        lines.append("        n_ok++;")
        lines.append(f'        printf("{sol_fmt}", {sol_args});')
        lines[-1] = lines[-1].replace('printf(', 'if (!quiet) printf(')
        lines.append("        zsp_block_alloc_destroy(ba);")
        lines.append("    }")
        lines.append("")
        lines.append("    clock_gettime(CLOCK_MONOTONIC, &ts_end);")
        lines.append("    long long bench_ns = (ts_end.tv_sec - ts_start.tv_sec) * 1000000000LL")
        lines.append("                       + (ts_end.tv_nsec - ts_start.tv_nsec);")
        lines.append('    fprintf(stderr, "BENCH_NS %lld  (%d solutions, %d failures, %d timeouts)\\n",'
                     ' bench_ns, n_ok, n_fail, n_timeout);')
        lines.append("    if (n_fail > 0) {")
        lines.append('        fprintf(stderr, "ERROR: %d UNSAT out of %d attempts (problem spec bug)\\n",'
                     ' n_fail, n_ok + n_fail + n_timeout);')
        lines.append("        return 1;")
        lines.append("    }")
        lines.append("")
        lines.append("    solve_problem_destroy(sp);")
        lines.append("    free(ctx_buf);")
        lines.append("    return 0;")
        lines.append("}")
        lines.append("")

        return "\n".join(lines)

    def _emit_constraint(self, lines: List[str], var_id_map: Dict[str, int],
                         constraint) -> str:
        """Emit C code to build an expression tree, return the ExprRef variable name."""
        if isinstance(constraint, ConstantConstraint):
            tmp = f"_e{self._tmp_counter}"; self._tmp_counter += 1
            lines.append(f"    ExprRef {tmp} = expr_const(sp, {constraint.value}LL, 0);")
            return tmp

        if isinstance(constraint, VariableRefConstraint):
            vid = var_id_map.get(constraint.variable.name)
            if vid is None:
                raise ValueError(f"Unknown variable: {constraint.variable.name}")
            tmp = f"_e{self._tmp_counter}"; self._tmp_counter += 1
            lines.append(f"    ExprRef {tmp} = expr_var(sp, {vid});")
            return tmp

        if isinstance(constraint, BinaryOpConstraint):
            lhs = self._emit_constraint(lines, var_id_map, constraint.left)
            rhs = self._emit_constraint(lines, var_id_map, constraint.right)
            op_c = _BINOP_C.get(constraint.op)
            if op_c is None:
                raise ValueError(f"Unsupported BinOp: {constraint.op}")
            tmp = f"_e{self._tmp_counter}"; self._tmp_counter += 1
            lines.append(f"    ExprRef {tmp} = expr_binary(sp, {op_c}, {lhs}, {rhs});")
            return tmp

        if isinstance(constraint, CompareConstraint):
            # If either side is a BinaryOp, introduce a temp variable so
            # the C compiler sees var==var or var==const (not BinOp==X).
            left_c = constraint.left
            right_c = constraint.right
            if isinstance(left_c, BinaryOpConstraint):
                left_c = self._introduce_temp(lines, var_id_map, left_c)
            if isinstance(right_c, BinaryOpConstraint):
                right_c = self._introduce_temp(lines, var_id_map, right_c)
            lhs = self._emit_constraint(lines, var_id_map, left_c)
            rhs = self._emit_constraint(lines, var_id_map, right_c)
            op_c = _CMPOP_C.get(constraint.op)
            if op_c is None:
                raise ValueError(f"Unsupported CmpOp: {constraint.op}")
            tmp = f"_e{self._tmp_counter}"; self._tmp_counter += 1
            lines.append(f"    ExprRef {tmp} = expr_binary(sp, {op_c}, {lhs}, {rhs});")
            return tmp

        if isinstance(constraint, BoolOpConstraint):
            op_c = "BIN_AND" if constraint.op == BoolOp.And else "BIN_OR"
            result = self._emit_constraint(lines, var_id_map, constraint.values[0])
            for val in constraint.values[1:]:
                rhs = self._emit_constraint(lines, var_id_map, val)
                tmp = f"_e{self._tmp_counter}"; self._tmp_counter += 1
                lines.append(f"    ExprRef {tmp} = expr_binary(sp, {op_c}, {result}, {rhs});")
                result = tmp
            return result

        raise ValueError(f"Unsupported constraint type: {type(constraint).__name__}")

    def _introduce_temp(self, lines: List[str], var_id_map: Dict[str, int],
                        binop) -> "VariableRefConstraint":
        """Decompose a BinaryOpConstraint into a temp variable + ADD constraint.

        Emits: problem_add_var(tmp, ...); problem_add_constraint(tmp == lhs op rhs);
        Returns a VariableRefConstraint referencing the new temp.
        """
        from zuspec.dataclasses.solver.core.variable import Variable as IRVariable
        from zuspec.dataclasses.solver.core.domain import IntDomain

        # Recursively decompose nested BinOps
        left_c = binop.left
        right_c = binop.right
        if isinstance(left_c, BinaryOpConstraint):
            left_c = self._introduce_temp(lines, var_id_map, left_c)
        if isinstance(right_c, BinaryOpConstraint):
            right_c = self._introduce_temp(lines, var_id_map, right_c)

        tmp_name = f"__c_tmp_{self._tmp_counter}"
        tmp_vid = len(var_id_map)
        var_id_map[tmp_name] = tmp_vid
        # 64-bit signed to avoid overflow
        lines.append(f"    problem_add_var(sp, {tmp_vid}, 64, 1,"
                     f" {-(1 << 62)}LL, {(1 << 62) - 1}LL);  /* {tmp_name} */")

        lhs_ref = self._emit_constraint(lines, var_id_map, left_c)
        rhs_ref = self._emit_constraint(lines, var_id_map, right_c)
        op_c = _BINOP_C.get(binop.op)
        if op_c is None:
            raise ValueError(f"Unsupported BinOp in temp: {binop.op}")

        tmp_ref = f"_e{self._tmp_counter}"; self._tmp_counter += 1
        lines.append(f"    ExprRef {tmp_ref} = expr_var(sp, {tmp_vid});")
        binop_ref = f"_e{self._tmp_counter}"; self._tmp_counter += 1
        lines.append(f"    ExprRef {binop_ref} = expr_binary(sp, {op_c},"
                     f" {lhs_ref}, {rhs_ref});")
        eq_ref = f"_e{self._tmp_counter}"; self._tmp_counter += 1
        lines.append(f"    ExprRef {eq_ref} = expr_binary(sp, BIN_EQ,"
                     f" {tmp_ref}, {binop_ref});")
        lines.append(f"    problem_add_constraint(sp, {eq_ref});")

        return VariableRefConstraint(
            variable=IRVariable(tmp_name, IntDomain([], 64, True)))
