"""SV Randomizer Generator.

Takes a @zdc.dataclass class and emits a complete SystemVerilog file
containing the user class, a *_randomizer subclass with a base64-encoded
SolveProblem string, and a testbench module.

The generated code uses the chandle-based DPI API (scalar/string/chandle
arguments only) so it works on all simulators including Verilator.

Usage::

    from zuspec.solver.sv_randomizer_gen import SVRandomizerGenerator
    sv_text = SVRandomizerGenerator().emit(MyDataclass)
"""
from __future__ import annotations

import base64
from typing import Any, Dict, List, Optional, Tuple


class SVRandomizerGenerator:
    """Generates SystemVerilog randomizer code from a @zdc.dataclass."""

    def emit(self, cls: type, module_name: Optional[str] = None) -> str:
        """Emit a complete SV file for the given class.

        Returns SV source text containing:
        - User class with rand fields
        - Randomizer subclass with base64 problem string
        - Testbench module
        """
        problem_bytes, var_id_map, fields = self._build_problem(cls)
        cls_name = cls.__name__
        if module_name is None:
            module_name = f"{cls_name}_harness"

        parts = []
        parts.append(self._emit_header(cls_name))
        parts.append(self._emit_user_class(cls_name, fields))
        parts.append(self._emit_randomizer_class(cls_name, problem_bytes,
                                                  var_id_map, fields))
        parts.append(self._emit_testbench(cls_name, module_name,
                                           len(var_id_map)))
        return "\n".join(parts)

    def emit_randomizer_class(self, cls: type) -> str:
        """Emit just the randomizer class (for embedding in a larger file)."""
        problem_bytes, var_id_map, fields = self._build_problem(cls)
        return self._emit_randomizer_class(cls.__name__, problem_bytes,
                                           var_id_map, fields)

    # ------------------------------------------------------------------ #
    # Internal                                                             #
    # ------------------------------------------------------------------ #

    def _build_problem(
        self, cls: type
    ) -> Tuple[bytes, Dict[str, int], List[Tuple[str, int, bool]]]:
        """Build the SolveProblem buffer from a @zdc.dataclass.

        Returns (problem_bytes, var_id_map, fields) where fields is a list
        of (name, width, is_signed) tuples.
        """
        from zuspec.dataclasses.solver._core_solve import _extract_struct_type
        from zuspec.dataclasses.solver.frontend.constraint_system_builder import (
            ConstraintSystemBuilder,
        )
        from zuspec.solver.ir_translator import IRTranslator
        from zuspec.solver.builder import SolveProblemBuilder

        struct_type = _extract_struct_type(cls())
        builder = ConstraintSystemBuilder()
        system = builder.build_from_struct(struct_type)

        translator = IRTranslator()
        sp_builder, var_id_map = translator.translate(system)
        problem_bytes = sp_builder.finalize_bytes()

        # Extract field metadata from the constraint system variables
        fields = []
        sorted_vars = sorted(var_id_map.items(), key=lambda x: x[1])
        for name, vid in sorted_vars:
            var = system.variables[name]
            from zuspec.dataclasses.solver.core.domain import IntDomain
            domain = var.domain
            width = domain.width if isinstance(domain, IntDomain) else 32
            is_signed = domain.signed if isinstance(domain, IntDomain) else False
            # Skip internal temp variables
            if name.startswith("__"):
                continue
            fields.append((name, width, is_signed))

        return problem_bytes, var_id_map, fields

    def _emit_header(self, cls_name: str) -> str:
        return (
            f"// Generated by SVRandomizerGenerator for {cls_name}\n"
            f"// DO NOT EDIT -- regenerate from the Python @dataclass.\n"
            f"\n"
        )

    def _emit_user_class(
        self, cls_name: str, fields: List[Tuple[str, int, bool]]
    ) -> str:
        lines = [f"class {cls_name};"]
        for name, width, is_signed in fields:
            sv_type = self._sv_type(width, is_signed)
            lines.append(f"  rand {sv_type} {name};")
        lines.append(f"endclass\n")
        return "\n".join(lines)

    def _emit_randomizer_class(
        self,
        cls_name: str,
        problem_bytes: bytes,
        var_id_map: Dict[str, int],
        fields: List[Tuple[str, int, bool]],
    ) -> str:
        rnd_name = f"{cls_name}_randomizer"
        b64_str = base64.b64encode(problem_bytes).decode("ascii")
        n_vars = len(var_id_map)

        lines = [
            f"class {rnd_name} extends zsp_randomizer_pkg::zsp_randomizer #({cls_name});",
            "",
        ]

        # Base64 problem data as a string constant
        lines.append(self._format_b64_string(b64_str, "PROBLEM_B64"))
        lines.append("")

        # get_problem_b64
        lines.append("  virtual function string get_problem_b64();")
        lines.append("    return PROBLEM_B64;")
        lines.append("  endfunction")
        lines.append("")

        # get_n_vars
        lines.append("  virtual function int unsigned get_n_vars();")
        lines.append(f"    return {n_vars};")
        lines.append("  endfunction")
        lines.append("")

        # apply_solution -- uses per-variable zsp_dpi_get_value_h calls
        lines.append(f"  virtual function void apply_solution(")
        lines.append(f"    {cls_name} obj, chandle ctx")
        lines.append(f"  );")
        for name, width, is_signed in fields:
            vid = var_id_map.get(name)
            if vid is not None:
                lines.append(
                    f"    obj.{name} = "
                    f"zsp_dpi_pkg::zsp_dpi_get_value_h(ctx, {vid});"
                )
        lines.append("  endfunction")
        lines.append("")

        lines.append("endclass")
        lines.append("")
        return "\n".join(lines)

    def _emit_testbench(
        self, cls_name: str, module_name: str, n_vars: int
    ) -> str:
        rnd_name = f"{cls_name}_randomizer"
        return (
            f"module {module_name};\n"
            f"  import zsp_dpi_pkg::*;\n"
            f"  import zsp_randomizer_pkg::*;\n"
            f"\n"
            f"  initial begin\n"
            f"    {cls_name} obj;\n"
            f"    {rnd_name} rnd;\n"
            f"    int n_solutions;\n"
            f"    int rc;\n"
            f"\n"
            f"    obj = new();\n"
            f"    rnd = new();\n"
            f"\n"
            f'    if (!$value$plusargs("n_solutions=%d", n_solutions))\n'
            f"      n_solutions = 10;\n"
            f"\n"
            f"    repeat (n_solutions) begin\n"
            f"      rc = rnd.randomize_obj(obj, $urandom());\n"
            f"      if (rc != 0) begin\n"
            f'        $display("ERROR: randomize failed rc=%0d", rc);\n'
            f"        $finish(1);\n"
            f"      end\n"
            f'      $display("SOL: %p", obj);\n'
            f"    end\n"
            f"\n"
            f"    rnd.cleanup();\n"
            f'    $display("PASS: %0d solutions generated", n_solutions);\n'
            f"    $finish;\n"
            f"  end\n"
            f"endmodule\n"
        )

    def _format_b64_string(self, b64: str, name: str) -> str:
        """Format a base64 string as a SV string constant.

        Splits into 76-char lines for readability using string concatenation.
        """
        line_len = 76
        if len(b64) <= line_len:
            return f'  localparam string {name} = "{b64}";'

        lines = [f"  localparam string {name} = {{"]
        for i in range(0, len(b64), line_len):
            chunk = b64[i:i + line_len]
            comma = "," if i + line_len < len(b64) else ""
            lines.append(f'    "{chunk}"{comma}')
        lines.append("  };")
        return "\n".join(lines)

    def _sv_type(self, width: int, is_signed: bool) -> str:
        """Return the SV type string for a given width and signedness."""
        if is_signed:
            if width == 32:
                return "int"
            return f"bit signed [{width-1}:0]"
        if width == 1:
            return "bit"
        return f"bit [{width-1}:0]"
