// DPI solver benchmark (no std::randomize -- for Verilator)

import "DPI-C" function longint bench_time_ns();
import zsp_dpi_pkg::*;

module bench_dpi_only;

  int N;
  longint t0, t1;
  real dpi_us;

  task bench_small();
    chandle ctx;
    int rc;
    ctx = zsp_dpi_compile_b64("AwAAAAIAAAAAAAAAUAAAALgAAAD/////AAAAAAAAAACwAAAAsAAAAAAAAAAAAAAA/////wAAAAAIAAAAAAAAAAAAAAAAAAAA/wAAAAAAAAAQAAAAAQAAAAgAAAAAAAAAAAAAAAAAAAD/AAAAAAAAADAAAAACAAAACAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAQAAAAAAAAABAAAAAQAAAAIAAAANAAAAcAAAAHgAAAD/////gAAAAAEAAAABAAAAAQAAAAIAAAACAAAADQAAAJgAAACgAAAAkAAAAKgAAAA=");
    if (ctx == null) $fatal(1, "small: compile failed");
    t0 = bench_time_ns();
    repeat (N) begin
      rc = zsp_dpi_solve_h(ctx, $urandom());
      if (rc != 0) $fatal(1, "small solve failed");
    end
    t1 = bench_time_ns();
    dpi_us = real'(t1 - t0) / 1000.0;
    zsp_dpi_release_h(ctx);
    $display("BENCH small  %0d vars  N=%0d  dpi=%.1f us  dpi/call=%.2f us",
             3, N, dpi_us, dpi_us/N);
  endtask

  task bench_medium();
    chandle ctx;
    int rc;
    ctx = zsp_dpi_compile_b64("CgAAAAkAAAAAAAAAMAEAALACAAD/////AAAAAAAAAACoAgAAqAIAAAAAAAAAAAAA/////wAAAAAgAAAAAAAAAAAAAAAAAAAA6AMAAAAAAAAQAAAAAQAAACAAAAAAAAAAAAAAAAAAAADoAwAAAAAAADAAAAACAAAAIAAAAAAAAAAAAAAAAAAAAOgDAAAAAAAAUAAAAAMAAAAgAAAAAAAAAAAAAAAAAAAA6AMAAAAAAABwAAAABAAAACAAAAAAAAAAAAAAAAAAAADoAwAAAAAAAJAAAAAFAAAAIAAAAAAAAAAAAAAAAAAAAOgDAAAAAAAAsAAAAAYAAAAgAAAAAAAAAAAAAAAAAAAA6AMAAAAAAADQAAAABwAAACAAAAAAAAAAAAAAAAAAAADoAwAAAAAAAPAAAAAIAAAAIAAAAAAAAAAAAAAAAAAAAOgDAAAAAAAAEAEAAAkAAAAgAAAAAAAAAAAAAAAAAAAA6AMAAAAAAAABAAAAAAAAAAEAAAABAAAAAgAAAA0AAABQAQAAWAEAAP////9gAQAAAQAAAAEAAAABAAAAAgAAAAIAAAANAAAAeAEAAIABAABwAQAAiAEAAAEAAAACAAAAAQAAAAMAAAACAAAADQAAAKABAACoAQAAmAEAALABAAABAAAAAwAAAAEAAAAEAAAAAgAAAA0AAADIAQAA0AEAAMABAADYAQAAAQAAAAQAAAABAAAABQAAAAIAAAANAAAA8AEAAPgBAADoAQAAAAIAAAEAAAAFAAAAAQAAAAYAAAACAAAADQAAABgCAAAgAgAAEAIAACgCAAABAAAABgAAAAEAAAAHAAAAAgAAAA0AAABAAgAASAIAADgCAABQAgAAAQAAAAcAAAABAAAACAAAAAIAAAANAAAAaAIAAHACAABgAgAAeAIAAAEAAAAIAAAAAQAAAAkAAAACAAAADQAAAJACAACYAgAAiAIAAKACAAA=");
    if (ctx == null) $fatal(1, "medium: compile failed");
    t0 = bench_time_ns();
    repeat (N) begin
      rc = zsp_dpi_solve_h(ctx, $urandom());
      if (rc != 0) $fatal(1, "medium solve failed");
    end
    t1 = bench_time_ns();
    dpi_us = real'(t1 - t0) / 1000.0;
    zsp_dpi_release_h(ctx);
    $display("BENCH medium %0d vars  N=%0d  dpi=%.1f us  dpi/call=%.2f us",
             10, N, dpi_us, dpi_us/N);
  endtask

  task bench_large();
    chandle ctx;
    int rc;
    ctx = zsp_dpi_compile_b64("FAAAABMAAAAAAAAAcAIAAIAFAAD/////AAAAAAAAAAB4BQAAeAUAAAAAAAAAAAAA/////wAAAAAQAAAAAAAAAAAAAAAAAAAA9AEAAAAAAAAQAAAAAQAAABAAAAAAAAAAAAAAAAAAAAD0AQAAAAAAADAAAAACAAAAEAAAAAAAAAAAAAAAAAAAAPQBAAAAAAAAUAAAAAMAAAAQAAAAAAAAAAAAAAAAAAAA9AEAAAAAAABwAAAABAAAABAAAAAAAAAAAAAAAAAAAAD0AQAAAAAAAJAAAAAFAAAAEAAAAAAAAAAAAAAAAAAAAPQBAAAAAAAAsAAAAAYAAAAQAAAAAAAAAAAAAAAAAAAA9AEAAAAAAADQAAAABwAAABAAAAAAAAAAAAAAAAAAAAD0AQAAAAAAAPAAAAAIAAAAEAAAAAAAAAAAAAAAAAAAAPQBAAAAAAAAEAEAAAkAAAAQAAAAAAAAAAAAAAAAAAAA9AEAAAAAAAAwAQAACgAAABAAAAAAAAAAAAAAAAAAAAD0AQAAAAAAAFABAAALAAAAEAAAAAAAAAAAAAAAAAAAAPQBAAAAAAAAcAEAAAwAAAAQAAAAAAAAAAAAAAAAAAAA9AEAAAAAAACQAQAADQAAABAAAAAAAAAAAAAAAAAAAAD0AQAAAAAAALABAAAOAAAAEAAAAAAAAAAAAAAAAAAAAPQBAAAAAAAA0AEAAA8AAAAQAAAAAAAAAAAAAAAAAAAA9AEAAAAAAADwAQAAEAAAABAAAAAAAAAAAAAAAAAAAAD0AQAAAAAAABACAAARAAAAEAAAAAAAAAAAAAAAAAAAAPQBAAAAAAAAMAIAABIAAAAQAAAAAAAAAAAAAAAAAAAA9AEAAAAAAABQAgAAEwAAABAAAAAAAAAAAAAAAAAAAAD0AQAAAAAAAAEAAAAAAAAAAQAAAAEAAAACAAAADQAAAJACAACYAgAA/////6ACAAABAAAAAQAAAAEAAAACAAAAAgAAAA0AAAC4AgAAwAIAALACAADIAgAAAQAAAAIAAAABAAAAAwAAAAIAAAANAAAA4AIAAOgCAADYAgAA8AIAAAEAAAADAAAAAQAAAAQAAAACAAAADQAAAAgDAAAQAwAAAAMAABgDAAABAAAABAAAAAEAAAAFAAAAAgAAAA0AAAAwAwAAOAMAACgDAABAAwAAAQAAAAUAAAABAAAABgAAAAIAAAANAAAAWAMAAGADAABQAwAAaAMAAAEAAAAGAAAAAQAAAAcAAAACAAAADQAAAIADAACIAwAAeAMAAJADAAABAAAABwAAAAEAAAAIAAAAAgAAAA0AAACoAwAAsAMAAKADAAC4AwAAAQAAAAgAAAABAAAACQAAAAIAAAANAAAA0AMAANgDAADIAwAA4AMAAAEAAAAJAAAAAQAAAAoAAAACAAAADQAAAPgDAAAABAAA8AMAAAgEAAABAAAACgAAAAEAAAALAAAAAgAAAA0AAAAgBAAAKAQAABgEAAAwBAAAAQAAAAsAAAABAAAADAAAAAIAAAANAAAASAQAAFAEAABABAAAWAQAAAEAAAAMAAAAAQAAAA0AAAACAAAADQAAAHAEAAB4BAAAaAQAAIAEAAABAAAADQAAAAEAAAAOAAAAAgAAAA0AAACYBAAAoAQAAJAEAACoBAAAAQAAAA4AAAABAAAADwAAAAIAAAANAAAAwAQAAMgEAAC4BAAA0AQAAAEAAAAPAAAAAQAAABAAAAACAAAADQAAAOgEAADwBAAA4AQAAPgEAAABAAAAEAAAAAEAAAARAAAAAgAAAA0AAAAQBQAAGAUAAAgFAAAgBQAAAQAAABEAAAABAAAAEgAAAAIAAAANAAAAOAUAAEAFAAAwBQAASAUAAAEAAAASAAAAAQAAABMAAAACAAAADQAAAGAFAABoBQAAWAUAAHAFAAA=");
    if (ctx == null) $fatal(1, "large: compile failed");
    t0 = bench_time_ns();
    repeat (N) begin
      rc = zsp_dpi_solve_h(ctx, $urandom());
      if (rc != 0) $fatal(1, "large solve failed");
    end
    t1 = bench_time_ns();
    dpi_us = real'(t1 - t0) / 1000.0;
    zsp_dpi_release_h(ctx);
    $display("BENCH large  %0d vars  N=%0d  dpi=%.1f us  dpi/call=%.2f us",
             20, N, dpi_us, dpi_us/N);
  endtask

  initial begin
    if (!$value$plusargs("N=%d", N))
      N = 10000;
    $display("=== DPI-only benchmark (N=%0d) ===", N);
    bench_small();
    bench_medium();
    bench_large();
    $display("=== Done ===");
    $finish;
  end

endmodule
