// Base class for DPI-based randomizers using zuspec-solver.
//
// Subclasses (generated by SVRandomizerGenerator) override
// get_problem_b64() and apply_solution().

package zsp_randomizer_pkg;

  import zsp_dpi_pkg::*;

  virtual class zsp_randomizer #(type T = int);

    // -- Pure virtual methods (overridden by generated subclass) -------

    // Return the problem data as a base64-encoded string.
    pure virtual function string get_problem_b64();

    // Return the number of rand fields.
    pure virtual function int unsigned get_n_vars();

    // Map solved values back to object fields using get_value_h calls.
    pure virtual function void apply_solution(T obj, chandle ctx);

    // -- Internal state -----------------------------------------------

    local chandle m_ctx;
    local bit     m_initialized;

    // -- Constructor --------------------------------------------------

    // NOTE: get_problem_b64() is pure virtual and cannot be safely called
    // here (Verilator resolves virtual calls during construction using the
    // base-class vtable, returning an empty string).  Initialization is
    // deferred to the first randomize_obj() call instead.
    function new();
      m_ctx         = null;
      m_initialized = 0;
    endfunction

    // -- Lazy initialization ------------------------------------------

    local function void _ensure_initialized();
      if (!m_initialized) begin
        string b64;
        b64 = get_problem_b64();
        m_ctx = zsp_dpi_compile_b64(b64);
        if (m_ctx == null)
          $fatal(1, "zsp_randomizer: compile failed");
        m_initialized = 1;
      end
    endfunction

    // -- Randomize ----------------------------------------------------

    virtual function int randomize_obj(T obj, longint seed = 0);
      int rc;
      _ensure_initialized();
      rc = zsp_dpi_solve_h(m_ctx, seed);
      if (rc == 0)
        apply_solution(obj, m_ctx);
      return rc;
    endfunction

    // -- Cleanup ------------------------------------------------------

    function void cleanup();
      if (m_ctx != null) begin
        zsp_dpi_release_h(m_ctx);
        m_ctx = null;
      end
    endfunction

  endclass

endpackage
